version: '2'
services:
    spring-webflux-mongodb:
        image: mongo:3.4.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/spring-webflux/mongodb/:/data/db/
