dist: trusty

language: java

jdk: openjdk8

services:
- docker

branches:
  only:
  - master

cache:
  directories:
  # We cache the SDK so we don't have to download it again on subsequent builds.
  - $HOME/google-cloud-sdk

env:
  global:
  # Do not prompt for user input when using any SDK methods.
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install: echo "This should be running tests for continuous integration"

install:
 - mvn clean cobertura:cobertura install -q

after_deploy:
  - if [[ $TRAVIS_COMMIT_MESSAGE == *"trigger build"* ]]; then docker:build ; fi ;

# Deploy  to Google Kubernetes Engine
after_success:
  - bash <(curl -s https://codecov.io/bash)
#- if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then ./deploy.sh; fi
