language: java

services:
- docker

branches:
  only:
  - master

cache:
  directories:
  # We cache the SDK so we don't have to download it again on subsequent builds.
  - $HOME/google-cloud-sdk

env:
  global:
  # Do not prompt for user input when using any SDK methods.
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

script: echo "This should be running tests for continuous integration"

install:
 - mvn -qB clean install docker:build

# Deploy  to Google Kubernetes Engine
after_success:
  - echo "Deploy to GKE"
#- if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then ./deploy.sh; fi
