spring:
  profiles: prod
  sleuth:
    sampler:
      probability: 0.1

security:
  oauth2:
    client:
      accessTokenUri: ${ACCESS_TOKEN_URI:https://spendingbetter.com/auth/oauth/token}
      userAuthorizationUri: ${AUTHORIZATION_URL:https://spendingbetter.com/auth/oauth/authorize}
      clientId: ${OAUTH_CLIENT_ID:client}
      clientSecret: ${OAUTH_CLIENT_SECRET:secret}
    resource:
      jwt:
        key-store: ${KEYSTORE:}
        key-store-password: ${KEYSTORE_PASSWORD:}
        key-alias: ${KEYSTORE_ALIAS:}
      user-info-uri: ${USER_INFO_URI:https://spendingbetter.com/auth/api/authenticatedUser}
