version: '3.2'
services:
    service-discovery:
        image: eureka-server
        container_name: service-discovery
        environment:
            - SPRING_REDIS_HOST=redisdb
            - SPRING_REDIS_PORT=6380
            - SPRING_PROFILES_ACTIVE=dev
            - SERVER_PORT=8761
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb-datasource:27018
            - SPRING_DATA_MONGODB_DATABASE=docker
        depends_on:
          - redisdb
          - mongodb-datasource
        ports:
            - 8761:8761
        volumes:
            - ./docker-entrypoint.sh:/docker-entrypoint.sh
        command: sh ./docker-entrypoint.sh redisdb:6380

    config-management:
        image: config-server
        container_name: config-management
        environment:
            - SPRING_REDIS_HOST=redisdb
            - SPRING_REDIS_PORT=6380
            - SPRING_PROFILES_ACTIVE=dev
            - SERVER_PORT=8888
            - EUREKA_SERVER=http://service-discovery:8761/eureka/
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb-datasource:27018
            - SPRING_DATA_MONGODB_DATABASE=docker
        depends_on:
          - service-discovery
        ports:
            - 8888:8888
        volumes:
            - ./docker-entrypoint.sh:/docker-entrypoint.sh
        command: sh ./docker-entrypoint.sh service-discovery:8761

    gateway:
        image: edge-server
        container_name: gateway
        environment:
            - SPRING_REDIS_HOST=redisdb
            - SPRING_REDIS_PORT=6380
            - X_ENCRYPT_KEY=b7fc7cec8e7aab24648723258da87a8d09ad7cef7b0a2842738884496a9fbb53
            - SPRING_PROFILES_ACTIVE=dev
            - SPRING_CLOUD_CONFIG_URI=http://config-management:8888
            - SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED=false
            - SERVER_PORT=9006
            - EUREKA_SERVER=http://service-discovery:8761/eureka/
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb-datasource:27018
            - SPRING_DATA_MONGODB_DATABASE=docker
        depends_on:
            - service-discovery
            - config-management
        ports:
            - 9006:9006
        volumes:
            - ./docker-entrypoint.sh:/docker-entrypoint.sh
        command: sh ./docker-entrypoint.sh config-management:8888

    monitoring:
        image: admin-server
        container_name: monitoring
        environment:
            - SPRING_REDIS_HOST=redisdb
            - SPRING_REDIS_PORT=6380
            - SPRING_PROFILES_ACTIVE=dev
            - SPRING_CLOUD_CONFIG_URI=http://config-management:8888
            - SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED=false
            - SERVER_PORT=9000
            - EUREKA_SERVER=http://service-discovery:8761/eureka/
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb-datasource:27018
            - SPRING_DATA_MONGODB_DATABASE=docker
        depends_on:
          - service-discovery
        ports:
            - 9000:9000

    react-webapp:
        build:
            context: ../react-webapp
            dockerfile: Dockerfile
        container_name: react-webapp
        environment:
            - REACT_APP_GATEWAY_URL=http://localhost:9006
            - PORT=3001
        ports:
            - 3001:3001
        links:
          - gateway
        volumes:
            - ./docker-entrypoint.sh:/tmp/docker-entrypoint.sh
        command: sh /tmp/docker-entrypoint.sh gateway:9006

    week-menu-api:
        build:
            context: ../nodejs-service
            dockerfile: Dockerfile
        container_name: week-menu-api
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            - CONFIG_SERVER=http://localhost:8888
            - SERVER_PORT=3002
            - MONGODB_URI=mongodb://mongodb-datasource:27018/docker
            - EUREKA_SERVER=service-discovery
            - EUREKA_PORT=8761
            - DEBUG=*
            - NODE_DEBUG=request
        depends_on:
            - service-discovery
            - config-management
        links:
          - service-discovery
          - config-management
        ports:
            - 3002:3002
        volumes:
            - ./docker-entrypoint.sh:/tmp/docker-entrypoint.sh
        command: sh /tmp/docker-entrypoint.sh config-management:8888

    person-api:
        image: person-service
        container_name: person-api
        environment:
            - X_ENCRYPT_KEY=b7fc7cec8e7aab24648723258da87a8d09ad7cef7b0a2842738884496a9fbb53
            - SPRING_PROFILES_ACTIVE=dev
            - SPRING_CLOUD_CONFIG_URI=http://config-management:8888
            - SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED=false
            - SERVER_PORT=8082
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb-datasource:27018
            - SPRING_DATA_MONGODB_DATABASE=docker
            - EUREKA_SERVER=http://service-discovery:8761/eureka/
        depends_on:
            - service-discovery
            - config-management
            - mongodb-datasource
        ports:
            - 8082:8082
        volumes:
            - ./docker-entrypoint.sh:/docker-entrypoint.sh
        command: sh ./docker-entrypoint.sh config-management:8888

    user-api:
        image: user-service
        container_name: user-api
        environment:
            - X_ENCRYPT_KEY=b7fc7cec8e7aab24648723258da87a8d09ad7cef7b0a2842738884496a9fbb53
            - SPRING_PROFILES_ACTIVE=dev
            - SPRING_CLOUD_CONFIG_URI=http://config-management:8888
            - SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED=false
            - SERVER_PORT=8083
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb-datasource:27018
            - SPRING_DATA_MONGODB_DATABASE=docker
            - EUREKA_SERVER=http://service-discovery:8761/eureka/
        links:
          - authentication-api
        ports:
            - 8083:8083
        volumes:
            - ./docker-entrypoint.sh:/docker-entrypoint.sh
        command: sh ./docker-entrypoint.sh authentication-api:8081

    authentication-api:
        image: authentication-service
        container_name: authentication-api
        environment:
            - X_ENCRYPT_KEY=b7fc7cec8e7aab24648723258da87a8d09ad7cef7b0a2842738884496a9fbb53
            - SPRING_PROFILES_ACTIVE=dev
            - SPRING_CLOUD_CONFIG_URI=http://config-management:8888
            - SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED=false
            - SERVER_PORT=8081
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb-datasource:27018
            - SPRING_DATA_MONGODB_DATABASE=docker
            - EUREKA_SERVER=http://service-discovery:8761/eureka/
        depends_on:
            - service-discovery
            - config-management
            - mongodb-datasource
        ports:
            - 8081:8081
        volumes:
            - ./docker-entrypoint.sh:/docker-entrypoint.sh
        command: sh ./docker-entrypoint.sh config-management:8888

    mongodb-datasource:
        image: mongo:3.4.10
        command: mongod --port 27018
        container_name: mongodb-datasource
        ports:
            - 27018:27018

    redisdb:
        image: redis:alpine
        container_name: redisdb
        command: redis-server --port 6380
        ports:
          - 6380:6380

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        environment:
          - EUREKA_SERVER=service-discovery
          - EUREKA_PORT=8761
        volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
          - 9090:9090
        depends_on:
          - service-discovery
        links:
          - service-discovery

    grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
        - 3000:3000

    setup_grafana_datasource:
        image: appropriate/curl
        container_name: setup_grafana_datasource
        depends_on:
          - grafana
        volumes:
          - ./create-datasource-and-dashboard.sh:/create.sh:ro
        command: /create.sh