version: '3.2'
services:
    service-discovery:
        image: eureka-server
        container_name: service-discovery
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - SERVER_PORT=8761
        ports:
            - 8761:8761

    config-management:
        image: config-server
        container_name: config-management
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - SERVER_PORT=8888
            - EUREKA_SERVER=http://service-discovery:8761/eureka/
        depends_on:
          - service-discovery
        ports:
            - 8888:8888
        volumes:
            - ./docker-entrypoint.sh:/docker-entrypoint.sh
        command: sh ./docker-entrypoint.sh service-discovery:8761

    gateway:
        image: edge-server
        container_name: gateway
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - SPRING_CLOUD_CONFIG_URI=http://config-management:8888
            - SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED=false
            - SERVER_PORT=9006
            - EUREKA_SERVER=http://service-discovery:8761/eureka/
            - COMPOSE_HTTP_TIMEOUT=300
        depends_on:
            - service-discovery
            - config-management
        ports:
            - 9006:9006
        volumes:
            - ./docker-entrypoint.sh:/docker-entrypoint.sh
        command: sh ./docker-entrypoint.sh config-management:8888

    monitoring:
        image: admin-server
        container_name: monitoring
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - SPRING_CLOUD_CONFIG_URI=http://config-management:8888
            - SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED=false
            - SERVER_PORT=9000
            - EUREKA_SERVER=http://service-discovery:8761/eureka/
        depends_on:
          - service-discovery
        ports:
            - 9000:9000

    react-webapp:
        build:
            context: ../react-webapp
            dockerfile: Dockerfile
        container_name: react-webapp
        environment:
            - REACT_APP_GATEWAY_URL=http://localhost:9006
        ports:
            - 3000:3000
        links:
          - gateway
        volumes:
            - ./docker-entrypoint.sh:/tmp/docker-entrypoint.sh
        command: sh /tmp/docker-entrypoint.sh gateway:9006

    week-menu-api:
        build:
            context: ../nodejs-service
            dockerfile: Dockerfile
        container_name: week-menu-api
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - SPRING_CLOUD_CONFIG_URI=http://localhost:8888
            - SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED=false
            - SERVER_PORT=3002
            - MONGODB_URI=mongodb://mongodb-datasource:27018/docker
            - EUREKA_SERVER=service-discovery
        depends_on:
            - service-discovery
            - config-management
        links:
          - service-discovery
          - config-management
        ports:
            - 3002:3002
        volumes:
            - ./docker-entrypoint.sh:/tmp/docker-entrypoint.sh
        command: sh /tmp/docker-entrypoint.sh config-management:8888

    person-api:
        image: person-service
        container_name: person-api
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - SPRING_CLOUD_CONFIG_URI=http://config-management:8888
            - SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED=false
            - SERVER_PORT=8082
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb-datasource:27018
            - SPRING_DATA_MONGODB_DATABASE=docker
            - EUREKA_SERVER=http://service-discovery:8761/eureka/
        depends_on:
            - service-discovery
            - config-management
            - mongodb-datasource
        ports:
            - 8082:8082
        volumes:
            - ./docker-entrypoint.sh:/docker-entrypoint.sh
        command: sh ./docker-entrypoint.sh config-management:8888

    user-api:
        image: user-service
        container_name: user-api
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - SPRING_CLOUD_CONFIG_URI=http://config-management:8888
            - SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED=false
            - SERVER_PORT=8083
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb-datasource:27018
            - SPRING_DATA_MONGODB_DATABASE=docker
            - EUREKA_SERVER=http://service-discovery:8761/eureka/
        links:
          - authentication-api
        ports:
            - 8083:8083
        volumes:
            - ./docker-entrypoint.sh:/docker-entrypoint.sh
        command: sh ./docker-entrypoint.sh authentication-api:8081

    authentication-api:
        image: authentication-service
        container_name: authentication-api
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - SPRING_CLOUD_CONFIG_URI=http://config-management:8888
            - SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED=false
            - SERVER_PORT=8081
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb-datasource:27018
            - SPRING_DATA_MONGODB_DATABASE=docker
            - EUREKA_SERVER=http://service-discovery:8761/eureka/
        depends_on:
            - service-discovery
            - config-management
            - mongodb-datasource
        ports:
            - 8081:8081
        volumes:
            - ./docker-entrypoint.sh:/docker-entrypoint.sh
        command: sh ./docker-entrypoint.sh config-management:8888

    mongodb-datasource:
        image: mongo:3.4.10
        command: mongod --port 27018
        container_name: mongodb-datasource
        ports:
            - 27018:27018