spring:
    application:
        name: authentication-service
    cloud:
        consul:
            config:
                fail-fast: ${FAIL_FAST:true}
                format: yaml
            discovery:
                instance-id: ${spring.application.name}:${random.value}
    main:
        allow-bean-definition-overriding: true
    config:
        import: consul:${consul_url:localhost:8500}
management:
    endpoints:
        web:
            exposure:
                include: '*'
            cors:
                allowed-origins: '*'
                allow-credentials: false
opentracing:
    spring:
        web:
            skip-pattern: "/actuator.*|/api-docs.*|/swagger.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream"
