apiVersion: v1
kind: Service
metadata:
  name: week-menu-api
  labels:
    app: week-menu-api
spec:
  ports:
    - name: http
      port: 8443
  selector:
    app: week-menu-api
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: week-menu-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: week-menu-api
        version: v1
    spec:
      containers:
        - name: week-menu-api
          image: eu.gcr.io/spring-boot-gke-243520/nodejs-week-menu-api:1.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          volumeMounts:
            - name: spendingbetter-cert-p12
              mountPath: "/etc/ssl/certs"
              readOnly: true
          env:
            - name: JAVA_OPTS
              value: -Xms256m -Xmx512m
            - name: SERVER_PORT
              value: "8443"
            - name: SPRING_PROFILES_ACTIVE
              value: google,prod
            - name: MONGODB_URI
              value: mongodb://mongodb:27017/docker
            - name: EUREKA_SERVER
              value: eureka-server
            - name: HOST_NAME
              value: week-menu-api
            - name: IP_ADDRESS
              value: week-menu-api
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: KEYSTORE_PASSWORD
            - name: KEYSTORE_FILE
              value: "/etc/ssl/certs/spendingbetter.com.p12"
          ports:
            - containerPort: 8443
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /actuator/health
              port: 8443
            initialDelaySeconds: 200
            periodSeconds: 5
      volumes:
        - name: spendingbetter-cert-p12
          secret:
            secretName: spendingbetter-cert-p12
