apiVersion: v1
kind: Service
metadata:
  name: admin-server
  labels:
    app: admin-server
spec:
  ports:
    - name: http
      port: 8443
  selector:
    app: admin-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: admin-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: admin-server
        version: v1
    spec:
      containers:
        - name: admin-server
          image: eu.gcr.io/spring-boot-gke-243520/admin-server:1.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          volumeMounts:
            - name: spendingbetter-cert-p12
              mountPath: "/etc/ssl/certs"
              readOnly: true
          env:
            - name: JAVA_OPTS
              value: -Xms256m -Xmx512m
            - name: SERVER_PORT
              value: "8443"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017
            - name: SPRING_DATA_MONGODB_DATABASE
              value: docker
            - name: SPRING_REDIS_HOST
              value: redis
            - name: EUREKA_SERVER
              value: https://eureka-server:8443/eureka/
            - name: SPRING_CLOUD_CONFIG_URI
              value: https://config-server:8443
            - name: SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED
              value: "false"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: SPRING_BOOT_ADMIN_CONTEXT_PATH
              value: /monitoring
            - name: LOGGING_LEVEL_ROOT
              value: error
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB
              value: debug
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: KEYSTORE_PASSWORD
            - name: KEYSTORE_FILE
              value: "/etc/ssl/certs/spendingbetter.com.p12"
          ports:
            - containerPort: 8443
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /actuator/health
              port: 8443
            initialDelaySeconds: 200
            periodSeconds: 5
      volumes:
        - name: spendingbetter-cert-p12
          secret:
            secretName: spendingbetter-cert-p12
