apiVersion: v1
kind: Service
metadata:
  name: config-server
  annotations:
    cloud.google.com/app-protocols: '{"https-port":"HTTPS","http-port":"HTTP"}'
  labels:
    app: config-server
spec:
  ports:
    - name: https-port
      port: 8443
    - name: http-port
      port: 8888
  selector:
    app: config-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: config-server
        version: v1
    spec:
      containers:
        - name: config-server
          image: eu.gcr.io/spring-boot-gke-243520/config-server:11.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          volumeMounts:
            - name: spendingbetter-crt
              mountPath: "/etc/crt"
              readOnly: true
            - name: spendingbetter-jks
              mountPath: "/etc/ssl_certs_jks"
              readOnly: true
          env:
            - name: JAVA_OPTS
              value: -Xms256m -Xmx512m
            - name: SERVER_PORT
              value: "8888"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017
            - name: SPRING_DATA_MONGODB_DATABASE
              value: docker
            - name: SPRING_REDIS_HOST
              value: redis
#            - name: EUREKA_CLIENT_ENABLED
#              value: "false"
#            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
#              value: "false"
            - name: EUREKA_SERVER
              value: http://eureka-server:8761/eureka/eureka/
            - name: KEYSTORE
              value: file:/etc/ssl_certs_jks/www.spendingbetter.com.jks
            - name: KEYSTORE_ALIAS
              value: spring-boot
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: KEYSTORE_PASSWORD
            - name: ACCESS_TOKEN_URI
              value: https://spendingbetter.com/auth/oauth/token
            - name: AUTHORIZATION_URL
              value: https://spendingbetter.com/auth/oauth/authorize
            - name: USER_INFO_URI
              value: https://spendingbetter.com/auth/api/authenticatedUser
          command: ["/bin/sh"]
          args: ["-c", "keytool -import -trustcacerts -alias spendingbetter.com -file /etc/crt/www.spendingbetter.com.crt -storepass changeit -keystore $JAVA_HOME/lib/security/cacerts -noprompt && $JAVA_CMD"]
          ports:
            - containerPort: 8888
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 200
            periodSeconds: 5
      volumes:
        - name: spendingbetter-crt
          secret:
            secretName: spendingbetter-crt
        - name: spendingbetter-jks
          secret:
            secretName: spendingbetter-jks
