apiVersion: v1
kind: Service
metadata:
  name: week-menu-api
  labels:
    app: week-menu-api
spec:
  ports:
    - name: http
      port: 3002
  selector:
    app: week-menu-api
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: week-menu-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: week-menu-api
        version: v1
    spec:
      containers:
        - name: week-menu-api
          image: eu.gcr.io/spring-boot-gke-243520/nodejs-week-menu-api:1.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          env:
            - name: JAVA_OPTS
              value: -Xmx256m -Xms512m -XX:MaxPermSize=512m
            - name: SERVER_PORT
              value: "3002"
            - name: SPRING_PROFILES_ACTIVE
              value: google
            - name: MONGODB_URI
              value: mongodb://mongodb:27017/docker
            - name: EUREKA_SERVER
              value: eureka-server
            - name: HOST_NAME
              value: week-menu-api
            - name: IP_ADDRESS
              value: week-menu-api
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
          ports:
            - containerPort: 3002
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 3002
            initialDelaySeconds: 200
            periodSeconds: 5