apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: nodejs-service
spec:
  ports:
    - name: http
      port: 3002
  selector:
    app: nodejs-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs-service
        version: v1
    spec:
      containers:
        - name: nodejs-service
          image: eu.gcr.io/spring-boot-gke-243520/nodejs-service:1.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          env:
            - name: JAVA_OPTS
              value: -Xmx256m -Xms512m -XX:MaxPermSize=512m
            - name: SERVER_PORT
              value: "3002"
            - name: SPRING_PROFILES_ACTIVE
              value: dev,docker
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017
            - name: SPRING_DATA_MONGODB_DATABASE
              value: docker
            - name: SPRING_REDIS_HOST
              value: redis
            - name: EUREKA_SERVER
              value: eureka-server
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8888
            - name: SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED
              value: "false"
            - name: HOST_NAME
              value: nodejs-service
            - name: IP_ADDRESS
              value: nodejs-service
            - name: NODE_DEBUG
              value: request
          ports:
            - containerPort: 3002
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 3002
            initialDelaySeconds: 200
            periodSeconds: 5