apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  ports:
    - name: https
      port: 8443
  selector:
    app: eureka-server
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-server
        version: v1
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
          - "spendingbetter.com"
      containers:
        - name: eureka-server
          image: eu.gcr.io/spring-boot-gke-243520/eureka-server:1.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          volumeMounts:
            - name: spendingbetter-p12
              mountPath: "/etc/ssl_certs_p12"
              readOnly: true
            - name: spendingbetter-crt
              mountPath: "/etc/crt"
              readOnly: true
          env:
            - name: JAVA_OPTS
              value: -Xms256m -Xmx512m
            - name: SERVER_PORT
              value: "8443"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017
            - name: SPRING_DATA_MONGODB_DATABASE
              value: docker
            - name: SPRING_REDIS_HOST
              value: redis
            - name: DEBUG
              value: "true"
            - name: SERVER_SSL_KEY_STORE
              value: "/etc/ssl_certs_p12/www.spendingbetter.com.p12"
            - name: SERVER_SSL_KEY_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: KEYSTORE_PASSWORD
            - name: SERVER_SSL_KEY_STORE_TYPE
              value: PKCS12
            - name: EUREKA_SERVER
              value: https://eureka-server:${server.port}/eureka/
            - name: SPRING_CLOUD_CLIENT_HOSTNAME
              value: spendingbetter.com
            - name: NON_SECURE_PORT_ENABLED
              value: "true"
            - name: SERVICE_SECURITY_TRUSTSTOREPATH
              value: /etc/ssl/truststore.jks
            - name: SERVICE_SECURITY_TRUSTSTOREPASSWORD
              value: ${SERVER_SSL_KEY_STORE_PASSWORD}
          command: ["/bin/sh"]
          args: ["-c", "keytool -import -trustcacerts -alias spendingbetter.com -file /etc/crt/www.spendingbetter.com.crt -storepass changeit -keystore $JAVA_HOME/lib/security/cacerts -noprompt
          && keytool -import -file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -keystore /etc/ssl/truststore.jks -storepass $(SERVER_SSL_KEY_STORE_PASSWORD) -alias kubernetes_ca -noprompt
          && $JAVA_CMD"]
          ports:
            - containerPort: 8443
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /actuator/health
              port: 8443
            initialDelaySeconds: 200
            periodSeconds: 5
      volumes:
        - name: spendingbetter-p12
          secret:
            secretName: spendingbetter-p12
        - name: spendingbetter-crt
          secret:
            secretName: spendingbetter-crt
