apiVersion: v1
kind: Service
metadata:
  name: user-service
  annotations:
    cloud.google.com/app-protocols: '{"https-port":"HTTPS"}'
  labels:
    app: user-service
spec:
  ports:
    - name: https-port
      port: 8443
  selector:
    app: user-service
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: eu.gcr.io/spring-boot-gke-243520/user-service:1.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          volumeMounts:
            - name: spendingbetter-jks
              mountPath: "/etc/ssl_certs"
              readOnly: true
          env:
            - name: JAVA_OPTS
              value: -Xms256m -Xmx512m -Djavax.net.ssl.trustStore=/etc/ssl/truststore.jks
            - name: SERVER_PORT
              value: "8443"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017
            - name: SPRING_DATA_MONGODB_DATABASE
              value: docker
            - name: SPRING_REDIS_HOST
              value: redis
            - name: EUREKA_SERVER
              value: https://eureka-server:8443/eureka/
            - name: SPRING_CLOUD_CONFIG_URI
              value: https://config-server:8443
            - name: SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED
              value: "false"
            - name: X_ENCRYPT_KEY
              value: b7fc7cec8e7aab24648723258da87a8d09ad7cef7b0a2842738884496a9fbb53
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_NON_SECURE_PORT_ENABLED
              value: "false"
            - name: EUREKA_INSTANCE_SECURE_PORT_ENABLED
              value: "true"
            - name: EUREKA_INSTANCE_SECURE_PORT
              value: "8443"
            - name: EUREKA_INSTANCE_STATUS_PAGE_URL
              value: https://localhost:${server.port}/actuator/info
            - name: EUREKA_INSTANCE_HEALTH_CHECK_URL
              value: https://localhost:${server.port}/actuator/health
            - name: EUREKA_INSTANCE_HOME_PAGE_URL
              value: https://localhost:${server.port}/
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: KEYSTORE_PASSWORD
            - name: KEYSTORE_FILE
              value: "/etc/ssl_certs/spendingbetter.com.jks"
          command: ["/bin/sh"]
          args: ["-c", "keytool -import -file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -keystore /etc/ssl/truststore.jks -storepass $(KEYSTORE_PASSWORD) -alias kubernetes_ca -noprompt && $JAVA_CMD"]
          ports:
            - containerPort: 8443
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /actuator/health
              port: 8443
            initialDelaySeconds: 200
            periodSeconds: 5
      volumes:
        - name: spendingbetter-jks
          secret:
            secretName: spendingbetter-jks
