apiVersion: v1
kind: Service
metadata:
  name: react-webapp
  labels:
    app: react-webapp
spec:
  ports:
    - name: http
      port: 3003
  selector:
    app: react-webapp
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: react-webapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: react-webapp
    spec:
      containers:
        - name: react-webapp
          image: eu.gcr.io/spring-boot-gke-243520/react-webapp:5.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          env:
            - name: PORT
              value: "3003"
            - name: REACT_APP_GATEWAY_URL
#              value: https://35.195.42.69
              value: https://spendingbetter.com
            - name: REACT_APP_EUREKA_URL
              value: https://spendingbetter.com/eureka
            - name: REACT_APP_MONITORING_URL
              value: https://spendingbetter.com/monitoring
            - name: REACT_APP_HOSTNAME
              value: ${HOSTNAME} - Production
          ports:
            - containerPort: 3003
