apiVersion: v1
kind: Service
metadata:
  name: person-service
  annotations:
    cloud.google.com/app-protocols: '{"https-port":"HTTPS","http-port":"HTTP"}'
  labels:
    app: person-service
spec:
  ports:
    - name: https-port
      port: 8443
    - name: http-port
      port: 8082
  selector:
    app: person-service
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: person-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: person-service
        version: v1
    spec:
      containers:
        - name: person-service
          image: eu.gcr.io/spring-boot-gke-243520/person-service:2.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          volumeMounts:
            - name: spendingbetter-p12
              mountPath: "/etc/ssl_certs_p12"
              readOnly: true
            - name: spendingbetter-crt
              mountPath: "/etc/crt"
              readOnly: true
          env:
            - name: JAVA_OPTS
              value: -Xms256m -Xmx512m
            - name: SERVER_PORT
              value: "8082"
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017
            - name: SPRING_DATA_MONGODB_DATABASE
              value: docker
            - name: SPRING_REDIS_HOST
              value: redis
            - name: EUREKA_SERVER
              value: http://eureka-server:8761/eureka/
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8888
#            - name: SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED
#              value: "false"
            - name: X_ENCRYPT_KEY
              value: b7fc7cec8e7aab24648723258da87a8d09ad7cef7b0a2842738884496a9fbb53
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
#            - name: EUREKA_INSTANCE_NON_SECURE_PORT_ENABLED
#              value: "false"
#            - name: EUREKA_INSTANCE_SECURE_PORT_ENABLED
#              value: "true"
#            - name: EUREKA_INSTANCE_SECURE_PORT
#              value: "8443"
#            - name: EUREKA_INSTANCE_STATUS_PAGE_URL
#              value: https://localhost:${server.port}/actuator/info
#            - name: EUREKA_INSTANCE_HEALTH_CHECK_URL
#              value: https://localhost:${server.port}/actuator/health
#            - name: EUREKA_INSTANCE_HOME_PAGE_URL
#              value: https://localhost:${server.port}/
#            - name: KEYSTORE_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: secrets
#                  key: KEYSTORE_PASSWORD
#            - name: KEYSTORE_FILE
#              value: "/etc/ssl_certs/www.spendingbetter.com.jks"
          command: ["/bin/sh"]
          args: ["-c", "keytool -import -trustcacerts -alias spendingbetter.com -file /etc/crt/www.spendingbetter.com.crt -storepass changeit -keystore $JAVA_HOME/lib/security/cacerts -noprompt && $JAVA_CMD"]
          ports:
            - containerPort: 8082
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 200
            periodSeconds: 5
      volumes:
        - name: spendingbetter-p12
          secret:
            secretName: spendingbetter-p12
        - name: spendingbetter-crt
          secret:
            secretName: spendingbetter-crt
