apiVersion: v1
kind: Service
metadata:
  name: week-menu-api
  annotations:
    cloud.google.com/app-protocols: '{"https-port":"HTTPS","http-port":"HTTP"}'
  labels:
    app: week-menu-api
spec:
  ports:
    - name: https-port
      port: 8443
    - name: http-port
      port: 3002
  selector:
    app: week-menu-api
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: week-menu-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: week-menu-api
        version: v1
    spec:
      containers:
        - name: week-menu-api
          image: eu.gcr.io/spring-boot-gke-243520/nodejs-week-menu-api:13.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          volumeMounts:
            - name: spendingbetter-crt
              mountPath: "/etc/crt"
              readOnly: true
            - name: spendingbetter-pub-key
              mountPath: "/etc/ssl_certs_pub"
              readOnly: true
          env:
            - name: JAVA_OPTS
              value: -Xms256m -Xmx512m
            - name: SERVER_PORT
              value: "3002"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: MONGODB_URI
              value: mongodb://mongodb:27017/docker
            - name: REDIS_SERVER
              value: redis
            - name: EUREKA_PATH
              value: /eureka/apps/
            - name: EUREKA_SERVER
              value: eureka-server-peer
            - name: HOST_NAME
              value: week-menu-api
            - name: IP_ADDRESS
              value: week-menu-api
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: PATH_PUBLIC_KEY
              value: /etc/ssl_certs_pub/www.spendingbetter.com.pub
            - name: NODE_DEBUG
              value: request
#            - name: NODE_ENV
#              value: production
#            - name: KEYSTORE_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: secrets
#                  key: KEYSTORE_PASSWORD
#            - name: KEYSTORE_FILE
#              value: "/etc/ssl/certs/www.spendingbetter.com.p12"
          ports:
            - containerPort: 3002
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 3002
            initialDelaySeconds: 200
            periodSeconds: 5
      volumes:
        - name: spendingbetter-crt
          secret:
            secretName: spendingbetter-crt
        - name: spendingbetter-pub-key
          secret:
            secretName: spendingbetter-pub-key
