apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        name: http
        number: 80
        protocol: HTTP
      hosts:
        - '*'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: eureka-server
spec:
  hosts:
    - "*"
  gateways:
    - istio-gateway
  http:
    - match:
        - uri:
            prefix: /service-discovery
      route:
        - destination:
            port:
              number: 8761
            host: eureka-server
    - match:
        - uri:
            prefix: /monitoring
      route:
        - destination:
            port:
              number: 9000
            host: admin-server
    - match:
        - uri:
            prefix: /config-server
      route:
        - destination:
            port:
              number: 8888
            host: config-server
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 3001
            host: react-webapp
