configuration:
    jwt:
        # This token must be encoded using Base64 (you can type `echo 'secret-key'|base64` on your command line)
        base64-secret: YTMwOTIwODE1MGMzOGExM2E4NDc5ZjhjMmQwMTdkNDJlZWZkOTE0YTMwNWUxMTgxMTFhZTI1ZDI3M2QyMTRmMjI5Yzg0ODBjYTUxYjVkY2I5ZmY0YmRkMzBlZjRjNDM2Y2NiYzhlZjQ0ODRjMWZlNzVmZjdjM2JiMjdkMjdmMjk=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000

management:
    endpoints:
        web:
            exposure:
                include: '*'

logging:
    file: ${LOGGING_PATH:/tmp/}${spring.application.name}.log

---
spring:
    profiles: dev
    sleuth:
        sampler:
            probability: 1

---
spring:
    profiles: prod
    sleuth:
        sampler:
            probability: 0.1

server:
    ssl:
        key-store: ${KEYSTORE_FILE:}
        key-store-password: ${KEYSTORE_PASSWORD:}
        key-store-type: ${KEYSTORE_TYPE:PKCS12}
        key-alias: ${KEYSTORE_ALIAS:spring-boot}
