zuul:
    ignoredServices: '*'
    ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
    routes:
        users-service:
            path: /api/users/**
            serviceId: user-service
            stripPrefix: false
            sensitiveHeaders:
        person-service:
            path: /api/persons/**
            serviceId: person-service
            stripPrefix: false
            sensitiveHeaders:
        authentication-service:
            path: /api/authenticate
            serviceId: authentication-service
            stripPrefix: false
            sensitiveHeaders:
        week-menu-api-service:
            path: /api/week-menu/**
            serviceId: week-menu-api
            stripPrefix: true
            sensitiveHeaders:

---
spring:
    profiles: heroku

zuul:
    routes:
        eureka-server:
            path: /eureka/**
            serviceId: EUREKA-SERVER
            stripPrefix: true
            sensitiveHeaders:

        config-server:
            path: /config/**
            serviceId: CONFIG-SERVER
            stripPrefix: true
            sensitiveHeaders:

        admin-server:
            path: /monitoring/**
            url: ADMIN-SERVER
            stripPrefix: true
            sensitiveHeaders:

        login:
            path: /login
            url: EUREKA-SERVER
            stripPrefix: true
            sensitiveHeaders:

        logout:
            path: /logout
            url: EUREKA-SERVER
            stripPrefix: true
            sensitiveHeaders:
