apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  annotations:
    cloud.google.com/app-protocols: '{"https-port":"HTTPS","http-port":"HTTP"}'
  labels:
    app: eureka-server
spec:
  ports:
    - name: https-port
      port: 8443
    - name: http-port
      port: 8761
  selector:
    app: eureka-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-server
        version: v1
    spec:
#      hostAliases:
#      - ip: "127.0.0.1"
#        hostnames:
#          - "spendingbetter.com"
      containers:
        - name: eureka-server
          image: eu.gcr.io/spring-boot-gke-243520/eureka-server:latest
#          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          volumeMounts:
            - name: spendingbetter-p12
              mountPath: "/etc/ssl_certs_p12"
              readOnly: true
            - name: spendingbetter-crt
              mountPath: "/etc/crt"
              readOnly: true
            - name: spendingbetter-jks
              mountPath: "/etc/ssl_certs_jks"
              readOnly: true
          env:
            - name: JAVA_OPTS
              value: -Xms256m -Xmx512m
            - name: SERVER_PORT
              value: "8761"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
#            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
#              value: "false"
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017
            - name: SPRING_DATA_MONGODB_DATABASE
              value: docker
            - name: SPRING_REDIS_HOST
              value: redis
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /eureka
            - name: ACCESS_TOKEN_URI
              value: https://YOUR_DOMAIN.com/auth/oauth/token
            - name: AUTHORIZATION_URL
              value: https://YOUR_DOMAIN.com/auth/oauth/authorize
            - name: USER_INFO_URI
              value: https://YOUR_DOMAIN.com/auth/api/authenticatedUser
#            - name: SERVER_SSL_KEY_STORE
#              value: "/etc/ssl_certs_p12/www.spendingbetter.com.p12"
#            - name: SERVER_SSL_KEY_STORE_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: secrets
#                  key: KEYSTORE_PASSWORD
#            - name: SERVER_SSL_KEY_STORE_TYPE
#              value: PKCS12
            - name: EUREKA_SERVER
              value: http://eureka-server-peer:${server.port}/eureka/
            - name: KEYSTORE
              value: file:/etc/ssl_certs_jks/www.spendingbetter.com.jks
            - name: KEYSTORE_ALIAS
              value: spring-boot
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: KEYSTORE_PASSWORD
#            - name: SPRING_CLOUD_CLIENT_HOSTNAME
#              value: eureka.spendingbetter.com
#            - name: NON_SECURE_PORT_ENABLED
#              value: "false"
#            - name: SERVICE_SECURITY_TRUSTSTOREPATH
#              value: /etc/ssl/truststore.jks
#            - name: SERVICE_SECURITY_TRUSTSTOREPASSWORD
#              value: ${SERVER_SSL_KEY_STORE_PASSWORD}
          command: ["/bin/sh"]
          args: ["-c", "keytool -import -trustcacerts -alias spendingbetter.com -file /etc/crt/www.spendingbetter.com.crt -storepass changeit -keystore $JAVA_HOME/lib/security/cacerts -noprompt && $JAVA_CMD"]
#          && keytool -import -file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -keystore /etc/ssl/truststore.jks -storepass $(SERVER_SSL_KEY_STORE_PASSWORD) -alias kubernetes_ca -noprompt
          ports:
            - containerPort: 8761
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /eureka/actuator/health
              port: 8761
            initialDelaySeconds: 200
            periodSeconds: 5
      volumes:
        - name: spendingbetter-p12
          secret:
            secretName: spendingbetter-p12
        - name: spendingbetter-crt
          secret:
            secretName: spendingbetter-crt
        - name: spendingbetter-jks
          secret:
            secretName: spendingbetter-jks
