apiVersion: v1
kind: Service
metadata:
  name: zipkin-server
  annotations:
    cloud.google.com/app-protocols: '{"https-port":"HTTPS","http-port":"HTTP"}'
  labels:
    app: zipkin-server
spec:
  ports:
    - name: https-port
      port: 8443
    - name: http-port
      port: 9411
  selector:
    app: zipkin-server
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin-server
  labels:
    app: zipkin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-server
  template:
    metadata:
      labels:
        app: zipkin-server
    spec:
      containers:
        - name: zipkin-server
          image: eu.gcr.io/spring-boot-gke-243520/zipkin-server:1.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          env:
            - name: JAVA_OPTS
              value: -verbose:gc -Xms256m -Xmx512m
            - name: SERVER_PORT
              value: "9411"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: STORAGE_TYPE
              value: mysql
            - name: MYSQL_HOST
              value: zipkin-mysql
            - name: MYSQL_USER
              value: zipkin
            - name: MYSQL_PASS
              value: zipkin
            - name: EUREKA_SERVER
              value: http://eureka-server:8761/eureka/eureka/
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8888
#            - name: SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED
#              value: "false"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
          ports:
            - containerPort: 9411
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 9411
            initialDelaySeconds: 200
            periodSeconds: 5
