apiVersion: v1
kind: Service
metadata:
  name: user-service
  annotations:
    cloud.google.com/app-protocols: '{"https-port":"HTTPS","http-port":"HTTP"}'
  labels:
    app: user-service
spec:
  ports:
    - name: https-port
      port: 8443
    - name: http-port
      port: 8083
  selector:
    app: user-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: fielcapao/microservices-design-patterns-user-service:latest
#          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          env:
            - name: JAVA_OPTS
              value: -Xms256m -Xmx512m
            - name: SERVER_PORT
              value: "8083"
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017
            - name: SPRING_DATA_MONGODB_DATABASE
              value: docker
            - name: SPRING_REDIS_HOST
              value: redis
            - name: SPRING_CLOUD_CONSUL_ENABLED
              value: "false"
            - name: OPENTRACING_JAEGER_ENABLED
              value: "false"
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAMESPACE
              value: "default"
          ports:
            - containerPort: 8083
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 1000
            periodSeconds: 5
