apiVersion: v1
kind: Service
metadata:
  name: python-service
  annotations:
    cloud.google.com/app-protocols: '{"https-port":"HTTPS","http-port":"HTTP"}'
  labels:
    app: python-service
spec:
  ports:
    - name: https-port
      port: 8443
    - name: http-port
      port: 3005
  selector:
    app: python-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python-service
        version: v1
    spec:
      containers:
        - name: python-service
          image: eu.gcr.io/spring-boot-gke-243520/python-service:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "30m"
            limits:
              memory: "256Mi"
              cpu: "30m"
          volumeMounts:
            - name: spendingbetter-pub-key
              mountPath: "/etc/ssl_certs_pub"
              readOnly: true
          env:
            - name: SERVER_PORT
              value: "3005"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: MONGODB_URI
              value: mongodb://mongodb:27017/docker
            - name: EUREKA_SERVER
              value: http://eureka-server-peer:8761/eureka/
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8888
            - name: MONGODB_URI
              value: mongodb://mongodb-datasource/docker
            - name: JWT_PUBLIC_KEY
              value: /etc/ssl_certs_pub/www.spendingbetter.com.pub
            - name: ENV_FILE_LOCATION
              value: ./.env
            - name: LOG_LEVEL
              value: TRACE
          ports:
            - containerPort: 3005
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 3005
            initialDelaySeconds: 200
            periodSeconds: 5
      volumes:
        - name: spendingbetter-pub-key
          secret:
            secretName: spendingbetter-pub-key
