apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  annotations:
    cloud.google.com/app-protocols: '{"https-port":"HTTPS","http-port":"HTTP"}'
  labels:
    app: authentication-service
spec:
  ports:
    - name: https-port
      port: 8443
    - name: http-port
      port: 9999
  selector:
    app: authentication-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: authentication-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: authentication-service
        version: v1
    spec:
      containers:
        - name: authentication-service
          image: eu.gcr.io/x-alcove-270419/authentication-service:latest
#          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          volumeMounts:
            - name: spendingbetter-crt
              mountPath: "/etc/crt"
              readOnly: true
            - name: spendingbetter-jks
              mountPath: "/etc/ssl_certs_jks"
              readOnly: true
          env:
            - name: JAVA_OPTS
              value: -Xms256m -Xmx512m
            - name: SERVER_PORT
              value: "9999"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017
            - name: SPRING_DATA_MONGODB_DATABASE
              value: docker
            - name: SPRING_REDIS_HOST
              value: redis
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
#            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
#              value: "false"
            - name: SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED
              value: "false"
#            - name: EUREKA_SERVER
#              value: http://eureka-server:8761/eureka/eureka/
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8888
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "true"
            - name: X_ENCRYPT_KEY
              value: b7fc7cec8e7aab24648723258da87a8d09ad7cef7b0a2842738884496a9fbb53
            - name: CONFIGURATION_AUTHORIZE_URLS
              value: "https://YOUR_DOMAIN.com/grafana/login/generic_oauth;https://YOUR_DOMAIN.com/eureka/login;https://YOUR_DOMAIN.com/monitoring/monitoring/login;https://YOUR_DOMAIN.com/login"
            - name: KEYSTORE
              value: /etc/ssl_certs_jks/www.spendingbetter.com.jks
            - name: KEYSTORE_ALIAS
              value: spring-boot
#            - name: LOGGING_LEVEL_COM_MICROSERVICE
#              value: debug
#            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB
#              value: debug
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
              value: debug
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: KEYSTORE_PASSWORD
#            - name: MANAGEMENT_ENDPOINTS_WEB_CORS_ALLOWED_ORIGINS
#              value: "*"
#            - name: MANAGEMENT_ENDPOINTS_WEB_CORS_ALLOWED_METHODS
#              value: "*"
#            - name: MANAGEMENT_ENDPOINTS_WEB_CORS_ALLOW_CREDENTIALS
#              value: "true"
          command: ["/bin/sh"]
          args: ["-c", "keytool -import -trustcacerts -alias spendingbetter.com -file /etc/crt/www.spendingbetter.com.crt -storepass changeit -keystore $JAVA_HOME/lib/security/cacerts -noprompt && $JAVA_CMD"]
          ports:
            - containerPort: 9999
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 9999
            initialDelaySeconds: 200
            periodSeconds: 5
      volumes:
        - name: spendingbetter-crt
          secret:
            secretName: spendingbetter-crt
        - name: spendingbetter-jks
          secret:
            secretName: spendingbetter-jks
