# This is a basic workflow to help you get started with Actions

name: CI - Build and push Docker images - Authentication Service

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: contains(toJson(github), 'build authentication-service')
    name: Build Jar and Build/Publish Docker Image

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up JDK 1.8
      - name: JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Build the Docker image with Maven
      - name: Build
        run: |
          mvn clean install -pl authentication-service -am -B -Dspring.profiles.active=travis jib:dockerBuild
          docker tag authentication-service:latest fielcapao/microservices-design-patterns/authentication-service:$GITHUB_SHA

      # Login to Dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Push the Docker image to Google Container Registry
      - name: Docker Publish
        run: |
          docker push fielcapao/microservices-design-patterns/authentication-service:$GITHUB_SHA

